name: vapee
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  loading_animations: ^2.1.0
  grouped_buttons: ^1.0.4
  searchable_dropdown: ^1.1.3
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+2
  custom_navigation_bar: ^0.2.6

flutter:
  uses-material-design: true

  assets:
    - image/
